/*
// if exception schdule code me aati hai then try catch will not handle the exception

setTimeout(() => {
    console.log("Hacking wifi....please wait....")
}, 1000);

try{
    setTimeout(() => {  //this is a schedule code and try catch will not handle the exception
    console.log(hello)
    }, 2000)
}
catch(err){
    console.log("Balle balle")
}
setTimeout(() => {
    console.log("Hacking router....please wait....")
}, 3000);

setTimeout(() => {
    console.log("Routers hacked....and ip address is: 120.100.50")
}, 4000);

*/
